### ISSUE TITLE
Uncaught Error: Could not find module `@ember/debug` imported from `appName/instance-initializers/axe-component`

### ISSUE THREAD

**Issue by ASH-Maan** [ember-a11y/ember-a11y-testing#107]
Installing ember-a11y-testing@0.5.2 on Ember app with ember-cli@2.12 stops page rendering and gives hard error: Uncaught Error: Could not find module `@ember/debug` imported from `appName/instance-initializers/axe-component`

Installing an older version such as 0.5.0 works fine.

**Comment by kaelinralav** [comment]
I'm facing the same on Installing ember-a11y-testing@0.5.4 with ember-cli@2.12.3 

Moving to v0.5.0 helped solve this in the testing environment. But in development, I got the following error, "ReferenceError: axe is not defined"

Any pointers are much appreciated!

**Comment by rwjblue** [comment]
The files in the app directory cannot use embers es module imports (why do we have non-“export only” files in the app dir again?!?!), they either need to be moved to addon folder and re-exported or remove the module imports from `@ember/**`...

**Comment by drewlee** [comment]
@rwjblue, looks like this may have been intentional as it's not possible to import the consuming app's config from the addon directory. However, I've found a workaround and went ahead with moving the files over in [https://github.com/ember-a11y/ember-a11y-testing/pull/130](https://github.com/ember-a11y/ember-a11y-testing/pull/130). Let me know if this looks ok. Thanks!
