### ISSUE TITLE
performance enhancement- requestIdleCallback?

### ISSUE THREAD

**Issue by MelSumner** [ember-a11y/ember-a11y-testing#87]
requestIdleCallback supports queuing a function to be called when the browser is idle. (https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback) 

Could this be used to increase the performance of the ember-a11y-testing addon?

**Comment by trentmwillis** [comment]
My two cents: This may be beneficial for the audit running within the application during development, but not for the testing environment.

For tests, we want it to be synchronous so that we are actually checking the DOM state that the user had intended to check. During development though, this seems more like a background task that doesn't necessarily need to block.

**Comment by MelSumner** [comment]
@trentmwillis what's a good way to separate testing vs development?

**Comment by trentmwillis** [comment]
Well currently we have the per-component audit, that only runs in development (not in testing mode): https://github.com/ember-a11y/ember-a11y-testing/blob/ef5c2debbb81776a34b87f9227762bf880e5e86a/app/instance-initializers/axe-component.js#L187

And then in tests, we have the `a11yAudit` helper.

**Comment by drewlee** [comment]
@MelSumner I think we should close this ticket out due to staleness. My 2 cents: somewhat averse to using this as it's still an experimental feature. This would also be tricky to integrate with tests due asynchronicity outside of the event loop. Could also conflict with the scheduler I setup to make axe-core work correctly with multiple component renders. requestIdleCallback seems to lend itself better for background-centric tasks such as fetch request and such, not so much for running a11y audit and UI updates.
