### ISSUE TITLE
Cannot modify dependent keys for `violationClasses` on `component-name` after it has been destroyed

### ISSUE THREAD

**Issue by ondrejsevcik** [ember-a11y/ember-a11y-testing#90]
Hi, first of all, thanks for this awesome addon, it makes my life much better :)

I've installed this addon in my app (Ember 2.16) and when I'm browsing through pages, I got a lot of these errors into the console. 

```
"Assertion Failed: Cannot modify dependent keys for `violationClasses` on `component-name` after it has been destroyed."
```
I know what it says in general, but I'm more curious why is this happening. Is it because I'm navigating too fast? Or is it some other issue? 

Thank you,
Ondrej

**Comment by trentmwillis** [comment]
I'm not 100% positive, but I believe this is because we run the audit asynchronously each time Ember's render-cycle is complete. See this line: https://github.com/ember-a11y/ember-a11y-testing/blob/ef5c2debbb81776a34b87f9227762bf880e5e86a/app/instance-initializers/axe-component.js#L189

So, I think what is happening is that we schedule a check for the component when you navigate, but the component is then destroyed before we actually run the audit. Thus, when the audit is run, you get the error in question.

**Comment by ondrejsevcik** [comment]
Yeah, that's probably it. I've tried to put a debugger in there and it crashed accessing this property when `this.get('isDestroyed')` was true. So I guess there is missing check if the component is destroyed already.

**Comment by trentmwillis** [comment]
Would you mind opening a PR to add the necessary check? It would be much appreciated!

**Comment by Samsinite** [comment]
I'm running into this error as well, and this definitely looks like the problem. But, I wanted to pose the question about if this event even needs scheduled at all. `didRender` is already called after render, couldn't it just directly invoke `audit`?

**Comment by Samsinite** [comment]
@trentmwillis I see an open PR is up: https://github.com/ember-a11y/ember-a11y-testing/pull/92. Would it be possible to get a patch release out for this?

**Comment by Robdel12** [comment]
Yeah, I'm trying to get travis happy (and upgrade the addon) in my branch. But right now I'm seeing test failures. Hopefully I can get it fixed up tonight.

**Comment by Robdel12** [comment]
This was closed with https://github.com/ember-a11y/ember-a11y-testing/commit/c8ee8d03386fba873c0773b04943e4626f62220a

I'll cut a release once CI passes :)
